
---
CREATE TABLE IF NOT EXISTS Movies (
Id UUID PRIMARY KEY,
Title TEXT NOT NULL,
Slug TEXT NOT NULL,
YearOfRelease INTEGER NOT NULL);
---
CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS movies_slug_idx
ON Movies
USING BTREE(Slug);
---
CREATE TABLE IF NOT EXISTS Genres (
movieId UUID references movies (Id),
name TEXT NOT NULL);
---
